
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ceshi.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.ceshi.block.ZuisnegzijingkuaiBlock;
import net.mcreator.ceshi.block.ZuishengkuangshiBlock;
import net.mcreator.ceshi.block.ZiyousongshikuangshiBlock;
import net.mcreator.ceshi.block.ZiyousongshikuaiBlock;
import net.mcreator.ceshi.block.YuansujingshikuaiBlock;
import net.mcreator.ceshi.block.YuanshikuangshiBlock;
import net.mcreator.ceshi.block.YiyishijieyuanmubanzhuanBlock;
import net.mcreator.ceshi.block.YiyishijiemuzhalanBlock;
import net.mcreator.ceshi.block.YiyishijiemubanlouqiBlock;
import net.mcreator.ceshi.block.YishijieyuanmumubanBlock;
import net.mcreator.ceshi.block.YishijiemuzhalanBlock;
import net.mcreator.ceshi.block.YishijiemubanStairsBlock;
import net.mcreator.ceshi.block.YishijiemubanSlabBlock;
import net.mcreator.ceshi.block.YishijiemubanPressurePlateBlock;
import net.mcreator.ceshi.block.YishijiemubanPlanksBlock;
import net.mcreator.ceshi.block.YishijiemubanFenceGateBlock;
import net.mcreator.ceshi.block.YishijiemubanFenceBlock;
import net.mcreator.ceshi.block.YishijiemubanButtonBlock;
import net.mcreator.ceshi.block.XiuxiumulouqiBlock;
import net.mcreator.ceshi.block.XiutiekuaiBlock;
import net.mcreator.ceshi.block.XiumuzhalanBlock;
import net.mcreator.ceshi.block.XiumuBlock;
import net.mcreator.ceshi.block.XinyuekuangshiBlock;
import net.mcreator.ceshi.block.XijaieyangengdiBlock;
import net.mcreator.ceshi.block.XiaoguanziBlock;
import net.mcreator.ceshi.block.ShizuoyuanshikuaiBlock;
import net.mcreator.ceshi.block.ShengzhangkuangshiBlock;
import net.mcreator.ceshi.block.ShengzhangbifeidakuaiBlock;
import net.mcreator.ceshi.block.ShenbanyanyuanshikuangshiBlock;
import net.mcreator.ceshi.block.ShenbanjianlaohuangyukuangshiBlock;
import net.mcreator.ceshi.block.Sanyueqidiaoxiang01Block;
import net.mcreator.ceshi.block.RanyuanmanaokuangshiBlock;
import net.mcreator.ceshi.block.Ranyuankuai2Block;
import net.mcreator.ceshi.block.MutankuaiBlock;
import net.mcreator.ceshi.block.Molakuai01Block;
import net.mcreator.ceshi.block.Moladui02Block;
import net.mcreator.ceshi.block.MmolazhilajitongBlock;
import net.mcreator.ceshi.block.ManyuejinshukuangshiBlock;
import net.mcreator.ceshi.block.LlianjiamolakuiaitaijieBlock;
import net.mcreator.ceshi.block.LlianjiamolakuaiqiangBlock;
import net.mcreator.ceshi.block.LlianjiamolakuaiBlock;
import net.mcreator.ceshi.block.LianjiaxiajiehejinkuaiBlock;
import net.mcreator.ceshi.block.LianjiamolakuaibankuaiBlock;
import net.mcreator.ceshi.block.LajitongBlock;
import net.mcreator.ceshi.block.JiuchanzhiyuankuaiBlock;
import net.mcreator.ceshi.block.JingzhimolakuaiBlock;
import net.mcreator.ceshi.block.JianlaokuangshiBlock;
import net.mcreator.ceshi.block.JianlaohuangyukuaiBlock;
import net.mcreator.ceshi.block.GanjinglajitongxiangziBlock;
import net.mcreator.ceshi.block.DisuishuijingtiBlock;
import net.mcreator.ceshi.block.Disuikuai1Block;
import net.mcreator.ceshi.block.DijingqinjingkuangshiBlock;
import net.mcreator.ceshi.block.DijingqingjinkuaiBlock;
import net.mcreator.ceshi.block.DaguanziBlock;
import net.mcreator.ceshi.block.D17Block;
import net.mcreator.ceshi.block.D16Block;
import net.mcreator.ceshi.block.D15Block;
import net.mcreator.ceshi.block.D14Block;
import net.mcreator.ceshi.block.D13Block;
import net.mcreator.ceshi.block.D12Block;
import net.mcreator.ceshi.block.D11Block;
import net.mcreator.ceshi.block.CshixiutiezhalanBlock;
import net.mcreator.ceshi.block.ChuangzaoxiaodengfasheqiBlock;
import net.mcreator.ceshi.block.ChiyuejinshukuangBlock;
import net.mcreator.ceshi.block.CeshixiaodengfasheqiBlock;
import net.mcreator.ceshi.block.CeshiguanziBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoStairsBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoSlabBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoPressurePlateBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoFenceGateBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoFenceBlock;
import net.mcreator.ceshi.block.Ceshi_mucaibaoButtonBlock;
import net.mcreator.ceshi.block.Ccaoyuanhehuamuban3Block;
import net.mcreator.ceshi.block.CaoyuansueciBlock;
import net.mcreator.ceshi.block.CaoyuanhekuaiBlock;
import net.mcreator.ceshi.block.CaoyuanhehuamubanBlock;
import net.mcreator.ceshi.block.Caoyuanhehuabuban2Block;
import net.mcreator.ceshi.block.Caomulouti21Block;
import net.mcreator.ceshi.block.Caomu36Block;
import net.mcreator.ceshi.block.Caomu35Block;
import net.mcreator.ceshi.block.Caomu34Block;
import net.mcreator.ceshi.block.Caomu33Block;
import net.mcreator.ceshi.block.Caomu32Block;
import net.mcreator.ceshi.block.Caomu31Block;
import net.mcreator.ceshi.block.Caomu26Block;
import net.mcreator.ceshi.block.Caomu25Block;
import net.mcreator.ceshi.block.Caomu24Block;
import net.mcreator.ceshi.block.Caomu22Block;
import net.mcreator.ceshi.block.Caomo23Block;
import net.mcreator.ceshi.block.CangsangshizhuanweiqiangBlock;
import net.mcreator.ceshi.block.CangsangshizhuantaijieBlock;
import net.mcreator.ceshi.block.CangsangshizhuanloutiBlock;
import net.mcreator.ceshi.block.CangsangshizhuanBlock;
import net.mcreator.ceshi.block.AixubingyukuangshiBlock;
import net.mcreator.ceshi.block.AixubingyufangkuIBlock;
import net.mcreator.ceshi.PrimogemcraftMod;

public class PrimogemcraftModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PrimogemcraftMod.MODID);
	public static final RegistryObject<Block> SANYUEQIDIAOXIANG_01 = REGISTRY.register("sanyueqidiaoxiang_01", () -> new Sanyueqidiaoxiang01Block());
	public static final RegistryObject<Block> CESHIXIAODENGFASHEQI = REGISTRY.register("ceshixiaodengfasheqi", () -> new CeshixiaodengfasheqiBlock());
	public static final RegistryObject<Block> CHUANGZAOXIAODENGFASHEQI = REGISTRY.register("chuangzaoxiaodengfasheqi", () -> new ChuangzaoxiaodengfasheqiBlock());
	public static final RegistryObject<Block> LAJITONG = REGISTRY.register("lajitong", () -> new LajitongBlock());
	public static final RegistryObject<Block> GANJINGLAJITONGXIANGZI = REGISTRY.register("ganjinglajitongxiangzi", () -> new GanjinglajitongxiangziBlock());
	public static final RegistryObject<Block> MMOLAZHILAJITONG = REGISTRY.register("mmolazhilajitong", () -> new MmolazhilajitongBlock());
	public static final RegistryObject<Block> MOLADUI_02 = REGISTRY.register("moladui_02", () -> new Moladui02Block());
	public static final RegistryObject<Block> XIAOGUANZI = REGISTRY.register("xiaoguanzi", () -> new XiaoguanziBlock());
	public static final RegistryObject<Block> DAGUANZI = REGISTRY.register("daguanzi", () -> new DaguanziBlock());
	public static final RegistryObject<Block> CESHIGUANZI = REGISTRY.register("ceshiguanzi", () -> new CeshiguanziBlock());
	public static final RegistryObject<Block> YUANSHIKUANGSHI = REGISTRY.register("yuanshikuangshi", () -> new YuanshikuangshiBlock());
	public static final RegistryObject<Block> SHENBANYANYUANSHIKUANGSHI = REGISTRY.register("shenbanyanyuanshikuangshi", () -> new ShenbanyanyuanshikuangshiBlock());
	public static final RegistryObject<Block> SHIZUOYUANSHIKUAI = REGISTRY.register("shizuoyuanshikuai", () -> new ShizuoyuanshikuaiBlock());
	public static final RegistryObject<Block> MOLAKUAI_01 = REGISTRY.register("molakuai_01", () -> new Molakuai01Block());
	public static final RegistryObject<Block> JINGZHIMOLAKUAI = REGISTRY.register("jingzhimolakuai", () -> new JingzhimolakuaiBlock());
	public static final RegistryObject<Block> LLIANJIAMOLAKUAI = REGISTRY.register("llianjiamolakuai", () -> new LlianjiamolakuaiBlock());
	public static final RegistryObject<Block> LLIANJIAMOLAKUAIQIANG = REGISTRY.register("llianjiamolakuaiqiang", () -> new LlianjiamolakuaiqiangBlock());
	public static final RegistryObject<Block> CANGSANGSHIZHUANWEIQIANG = REGISTRY.register("cangsangshizhuanweiqiang", () -> new CangsangshizhuanweiqiangBlock());
	public static final RegistryObject<Block> ZIYOUSONGSHIKUANGSHI = REGISTRY.register("ziyousongshikuangshi", () -> new ZiyousongshikuangshiBlock());
	public static final RegistryObject<Block> JIANLAOKUANGSHI = REGISTRY.register("jianlaokuangshi", () -> new JianlaokuangshiBlock());
	public static final RegistryObject<Block> SHENBANJIANLAOHUANGYUKUANGSHI = REGISTRY.register("shenbanjianlaohuangyukuangshi", () -> new ShenbanjianlaohuangyukuangshiBlock());
	public static final RegistryObject<Block> ZUISHENGKUANGSHI = REGISTRY.register("zuishengkuangshi", () -> new ZuishengkuangshiBlock());
	public static final RegistryObject<Block> SHENGZHANGKUANGSHI = REGISTRY.register("shengzhangkuangshi", () -> new ShengzhangkuangshiBlock());
	public static final RegistryObject<Block> DIJINGQINJINGKUANGSHI = REGISTRY.register("dijingqinjingkuangshi", () -> new DijingqinjingkuangshiBlock());
	public static final RegistryObject<Block> RANYUANMANAOKUANGSHI = REGISTRY.register("ranyuanmanaokuangshi", () -> new RanyuanmanaokuangshiBlock());
	public static final RegistryObject<Block> AIXUBINGYUKUANGSHI = REGISTRY.register("aixubingyukuangshi", () -> new AixubingyukuangshiBlock());
	public static final RegistryObject<Block> XINYUEKUANGSHI = REGISTRY.register("xinyuekuangshi", () -> new XinyuekuangshiBlock());
	public static final RegistryObject<Block> CHIYUEJINSHUKUANG = REGISTRY.register("chiyuejinshukuang", () -> new ChiyuejinshukuangBlock());
	public static final RegistryObject<Block> MANYUEJINSHUKUANGSHI = REGISTRY.register("manyuejinshukuangshi", () -> new ManyuejinshukuangshiBlock());
	public static final RegistryObject<Block> ZIYOUSONGSHIKUAI = REGISTRY.register("ziyousongshikuai", () -> new ZiyousongshikuaiBlock());
	public static final RegistryObject<Block> JIANLAOHUANGYUKUAI = REGISTRY.register("jianlaohuangyukuai", () -> new JianlaohuangyukuaiBlock());
	public static final RegistryObject<Block> ZUISNEGZIJINGKUAI = REGISTRY.register("zuisnegzijingkuai", () -> new ZuisnegzijingkuaiBlock());
	public static final RegistryObject<Block> SHENGZHANGBIFEIDAKUAI = REGISTRY.register("shengzhangbifeidakuai", () -> new ShengzhangbifeidakuaiBlock());
	public static final RegistryObject<Block> DIJINGQINGJINKUAI = REGISTRY.register("dijingqingjinkuai", () -> new DijingqingjinkuaiBlock());
	public static final RegistryObject<Block> RANYUANKUAI_2 = REGISTRY.register("ranyuankuai_2", () -> new Ranyuankuai2Block());
	public static final RegistryObject<Block> AIXUBINGYUFANGKU_I = REGISTRY.register("aixubingyufangku_i", () -> new AixubingyufangkuIBlock());
	public static final RegistryObject<Block> YUANSUJINGSHIKUAI = REGISTRY.register("yuansujingshikuai", () -> new YuansujingshikuaiBlock());
	public static final RegistryObject<Block> JIUCHANZHIYUANKUAI = REGISTRY.register("jiuchanzhiyuankuai", () -> new JiuchanzhiyuankuaiBlock());
	public static final RegistryObject<Block> MUTANKUAI = REGISTRY.register("mutankuai", () -> new MutankuaiBlock());
	public static final RegistryObject<Block> LIANJIAXIAJIEHEJINKUAI = REGISTRY.register("lianjiaxiajiehejinkuai", () -> new LianjiaxiajiehejinkuaiBlock());
	public static final RegistryObject<Block> CAOYUANHEKUAI = REGISTRY.register("caoyuanhekuai", () -> new CaoyuanhekuaiBlock());
	public static final RegistryObject<Block> CANGSANGSHIZHUAN = REGISTRY.register("cangsangshizhuan", () -> new CangsangshizhuanBlock());
	public static final RegistryObject<Block> DISUIKUAI_1 = REGISTRY.register("disuikuai_1", () -> new Disuikuai1Block());
	public static final RegistryObject<Block> XIUTIEKUAI = REGISTRY.register("xiutiekuai", () -> new XiutiekuaiBlock());
	public static final RegistryObject<Block> YISHIJIEYUANMUMUBAN = REGISTRY.register("yishijieyuanmumuban", () -> new YishijieyuanmumubanBlock());
	public static final RegistryObject<Block> YISHIJIEMUBAN_PLANKS = REGISTRY.register("yishijiemuban_planks", () -> new YishijiemubanPlanksBlock());
	public static final RegistryObject<Block> D_11 = REGISTRY.register("d_11", () -> new D11Block());
	public static final RegistryObject<Block> CAOYUANHEHUAMUBAN = REGISTRY.register("caoyuanhehuamuban", () -> new CaoyuanhehuamubanBlock());
	public static final RegistryObject<Block> CAOYUANHEHUABUBAN_2 = REGISTRY.register("caoyuanhehuabuban_2", () -> new Caoyuanhehuabuban2Block());
	public static final RegistryObject<Block> CCAOYUANHEHUAMUBAN_3 = REGISTRY.register("ccaoyuanhehuamuban_3", () -> new Ccaoyuanhehuamuban3Block());
	public static final RegistryObject<Block> XIUMU = REGISTRY.register("xiumu", () -> new XiumuBlock());
	public static final RegistryObject<Block> YIYISHIJIEMUBANLOUQI = REGISTRY.register("yiyishijiemubanlouqi", () -> new YiyishijiemubanlouqiBlock());
	public static final RegistryObject<Block> YISHIJIEMUBAN_STAIRS = REGISTRY.register("yishijiemuban_stairs", () -> new YishijiemubanStairsBlock());
	public static final RegistryObject<Block> D_12 = REGISTRY.register("d_12", () -> new D12Block());
	public static final RegistryObject<Block> LLIANJIAMOLAKUIAITAIJIE = REGISTRY.register("llianjiamolakuiaitaijie", () -> new LlianjiamolakuiaitaijieBlock());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_STAIRS = REGISTRY.register("ceshi_mucaibao_stairs", () -> new Ceshi_mucaibaoStairsBlock());
	public static final RegistryObject<Block> CAOMULOUTI_21 = REGISTRY.register("caomulouti_21", () -> new Caomulouti21Block());
	public static final RegistryObject<Block> CAOMU_31 = REGISTRY.register("caomu_31", () -> new Caomu31Block());
	public static final RegistryObject<Block> XIUXIUMULOUQI = REGISTRY.register("xiuxiumulouqi", () -> new XiuxiumulouqiBlock());
	public static final RegistryObject<Block> CANGSANGSHIZHUANLOUTI = REGISTRY.register("cangsangshizhuanlouti", () -> new CangsangshizhuanloutiBlock());
	public static final RegistryObject<Block> YIYISHIJIEYUANMUBANZHUAN = REGISTRY.register("yiyishijieyuanmubanzhuan", () -> new YiyishijieyuanmubanzhuanBlock());
	public static final RegistryObject<Block> YISHIJIEMUBAN_SLAB = REGISTRY.register("yishijiemuban_slab", () -> new YishijiemubanSlabBlock());
	public static final RegistryObject<Block> D_13 = REGISTRY.register("d_13", () -> new D13Block());
	public static final RegistryObject<Block> LIANJIAMOLAKUAIBANKUAI = REGISTRY.register("lianjiamolakuaibankuai", () -> new LianjiamolakuaibankuaiBlock());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_SLAB = REGISTRY.register("ceshi_mucaibao_slab", () -> new Ceshi_mucaibaoSlabBlock());
	public static final RegistryObject<Block> CAOMU_22 = REGISTRY.register("caomu_22", () -> new Caomu22Block());
	public static final RegistryObject<Block> CAOMU_32 = REGISTRY.register("caomu_32", () -> new Caomu32Block());
	public static final RegistryObject<Block> CANGSANGSHIZHUANTAIJIE = REGISTRY.register("cangsangshizhuantaijie", () -> new CangsangshizhuantaijieBlock());
	public static final RegistryObject<Block> YIYISHIJIEMUZHALAN = REGISTRY.register("yiyishijiemuzhalan", () -> new YiyishijiemuzhalanBlock());
	public static final RegistryObject<Block> YISHIJIEMUBAN_FENCE_GATE = REGISTRY.register("yishijiemuban_fence_gate", () -> new YishijiemubanFenceGateBlock());
	public static final RegistryObject<Block> D_15 = REGISTRY.register("d_15", () -> new D15Block());
	public static final RegistryObject<Block> CAOMU_24 = REGISTRY.register("caomu_24", () -> new Caomu24Block());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_FENCE_GATE = REGISTRY.register("ceshi_mucaibao_fence_gate", () -> new Ceshi_mucaibaoFenceGateBlock());
	public static final RegistryObject<Block> CAOMU_34 = REGISTRY.register("caomu_34", () -> new Caomu34Block());
	public static final RegistryObject<Block> YISHIJIEMUZHALAN = REGISTRY.register("yishijiemuzhalan", () -> new YishijiemuzhalanBlock());
	public static final RegistryObject<Block> YISHIJIEMUBAN_FENCE = REGISTRY.register("yishijiemuban_fence", () -> new YishijiemubanFenceBlock());
	public static final RegistryObject<Block> D_14 = REGISTRY.register("d_14", () -> new D14Block());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_FENCE = REGISTRY.register("ceshi_mucaibao_fence", () -> new Ceshi_mucaibaoFenceBlock());
	public static final RegistryObject<Block> CAOMO_23 = REGISTRY.register("caomo_23", () -> new Caomo23Block());
	public static final RegistryObject<Block> CAOMU_33 = REGISTRY.register("caomu_33", () -> new Caomu33Block());
	public static final RegistryObject<Block> XIUMUZHALAN = REGISTRY.register("xiumuzhalan", () -> new XiumuzhalanBlock());
	public static final RegistryObject<Block> XIJAIEYANGENGDI = REGISTRY.register("xijaieyangengdi", () -> new XijaieyangengdiBlock());
	public static final RegistryObject<Block> CSHIXIUTIEZHALAN = REGISTRY.register("cshixiutiezhalan", () -> new CshixiutiezhalanBlock());
	public static final RegistryObject<Block> DISUISHUIJINGTI = REGISTRY.register("disuishuijingti", () -> new DisuishuijingtiBlock());
	public static final RegistryObject<Block> CAOYUANSUECI = REGISTRY.register("caoyuansueci", () -> new CaoyuansueciBlock());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_PRESSURE_PLATE = REGISTRY.register("ceshi_mucaibao_pressure_plate", () -> new Ceshi_mucaibaoPressurePlateBlock());
	public static final RegistryObject<Block> CAOMU_25 = REGISTRY.register("caomu_25", () -> new Caomu25Block());
	public static final RegistryObject<Block> CAOMU_35 = REGISTRY.register("caomu_35", () -> new Caomu35Block());
	public static final RegistryObject<Block> YISHIJIEMUBAN_PRESSURE_PLATE = REGISTRY.register("yishijiemuban_pressure_plate", () -> new YishijiemubanPressurePlateBlock());
	public static final RegistryObject<Block> D_16 = REGISTRY.register("d_16", () -> new D16Block());
	public static final RegistryObject<Block> CESHI_MUCAIBAO_BUTTON = REGISTRY.register("ceshi_mucaibao_button", () -> new Ceshi_mucaibaoButtonBlock());
	public static final RegistryObject<Block> CAOMU_26 = REGISTRY.register("caomu_26", () -> new Caomu26Block());
	public static final RegistryObject<Block> CAOMU_36 = REGISTRY.register("caomu_36", () -> new Caomu36Block());
	public static final RegistryObject<Block> YISHIJIEMUBAN_BUTTON = REGISTRY.register("yishijiemuban_button", () -> new YishijiemubanButtonBlock());
	public static final RegistryObject<Block> D_17 = REGISTRY.register("d_17", () -> new D17Block());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			Sanyueqidiaoxiang01Block.registerRenderLayer();
			LajitongBlock.registerRenderLayer();
			GanjinglajitongxiangziBlock.registerRenderLayer();
			MmolazhilajitongBlock.registerRenderLayer();
			Moladui02Block.registerRenderLayer();
			XiaoguanziBlock.registerRenderLayer();
			DaguanziBlock.registerRenderLayer();
			CeshiguanziBlock.registerRenderLayer();
			LlianjiamolakuaiqiangBlock.registerRenderLayer();
			CangsangshizhuanweiqiangBlock.registerRenderLayer();
			Ranyuankuai2Block.registerRenderLayer();
			XiuxiumulouqiBlock.registerRenderLayer();
			YiyishijiemuzhalanBlock.registerRenderLayer();
			YishijiemuzhalanBlock.registerRenderLayer();
			XiumuzhalanBlock.registerRenderLayer();
			XijaieyangengdiBlock.registerRenderLayer();
			CshixiutiezhalanBlock.registerRenderLayer();
			DisuishuijingtiBlock.registerRenderLayer();
			CaoyuansueciBlock.registerRenderLayer();
		}
	}
}
